version: '3'
services:
  client:
    container_name: mangamonkey
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    restart: always

  server:
    container_name: mangamonkey_manga
    build: ./manga
    volumes:
      - ./manga:/usr/src/app
    ports:
      - "5000:5000"
    restart: always