version: '3'
services:
  db:
    container_name: mangamonkey-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manga_root
      MYSQL_DATABASE: mangamonkey

  client:
    container_name: mangamonkey
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    restart: always

  server:
    container_name: mangamonkey_manga
    build: ./manga
    volumes:
      - ./manga:/usr/src/app
    ports:
      - "5000:5000"
    restart: always

  users:
    container_name: mangamonkey_users
    build: ./user
    env_file:
      - ./user/.env
    volumes:
      - ./user:/usr/src/app
    ports:
      - "5001:5001"
    restart: always
